export class Profile {
    id!:number;
    name!:string;
    location!:string;
    gender!:string;
    dateOfJoining!:Date;
    designation!:string;
    category!:string;
    projectId!:number;
    leadId!:number;
    organizationId!:number;
    clientCounterpartId!:number;
    band!:number;
    dateOfLeaving!:Date;
    projectIdName!:string;
    leadIdName!:string;
    organizationIdName!:string;
    clientCounterpartIdName!:string;
    bandName!:string;
    email!:string;
}